package thttp

import (
	"errors"
	"fmt"
	"math/rand"
	"net/http"
	"strconv"
	"time"
)

// OAuth2Authenticator is the OAuth2 authenticator.
type OAuth2Authenticator struct {
	Nonce uint64 // This parameter participates in signature calculation. A random positive integer. Automatically generated by the SDK by default.

	// This parameter participates in signature calculation. Current UNIX timestamp, records the time when the API request was initiated. Defaults to the current timestamp.
	//
	// For example 1529223702, in seconds. Note: if it differs from the server time by more than 5 minutes, a signature expiration error will occur.
	Timestamp string
	Action    string // Interface name of the operation. Note: some interfaces do not require this parameter; the API documentation will specifically indicate this, and passing it will have no effect.
	Region    string // Region parameter, used to identify which region's data to operate on. Note: some interfaces do not require this parameter; the API documentation will specifically indicate this.

	AccessToken string // Token returned after successful OAuth2.0 authentication.
	OpenId      string // User information after successful OAuth2.0 authentication.
}

func (oauth2 OAuth2Authenticator) AuthHeader(httpReq *http.Request) error {

	if httpReq.Header.Get(HTTPHeaderContentType) == "" {
		httpReq.Header.Set(HTTPHeaderContentType, DefaultContentType)
	}

	if oauth2.AccessToken == "" {
		return errors.New("OAuth2 authenticator AccessToken can't be empty")
	}
	httpReq.Header.Set(HeaderAccessToken, oauth2.AccessToken)
	if oauth2.OpenId == "" {
		return errors.New("OAuth2 authenticator OpenId can't be empty")
	}
	httpReq.Header.Set(HeaderOpenId, oauth2.OpenId)
	if oauth2.Nonce == 0 {
		ts := time.Now().UnixMilli()
		rng := rand.New(rand.NewSource(time.Now().UnixNano()))
		rs := fmt.Sprintf("%06d", rng.Intn(1000000))
		ri, _ := strconv.Atoi(rs)
		oauth2.Nonce = uint64(ts)*1000000 + uint64(ri)
	}
	httpReq.Header.Set(XTCHeaderNonce, fmt.Sprint(oauth2.Nonce))

	if oauth2.Action != "" {
		httpReq.Header.Set(XTCHeaderAction, oauth2.Action)
	}

	if oauth2.Region != "" {
		httpReq.Header.Set(XTCHeaderRegion, oauth2.Region)
	}

	if oauth2.Timestamp == "" {
		oauth2.Timestamp = fmt.Sprint(time.Now().Unix())
	}
	httpReq.Header.Set(XTCHeaderTimestamp, oauth2.Timestamp)
	return nil
}

// JsonAuthenticator is the JSON format authenticator.
type JsonAuthenticator struct {
}

func (JsonAuthenticator) AuthHeader(httpReq *http.Request) error {

	if httpReq.Header.Get(HTTPHeaderContentType) == "" {
		httpReq.Header.Set(HTTPHeaderContentType, DefaultContentType)
	}

	return nil
}

var DefaultJsonAuthenticator Authentication = &JsonAuthenticator{}
