// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.35.1
// source: tmeet_wss.proto

package wsspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WebSocket frame header.
type Head struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrameType uint32 `protobuf:"varint,1,opt,name=frame_type,json=frameType,proto3" json:"frame_type,omitempty"` // Always 1.
	CmdType   uint32 `protobuf:"varint,2,opt,name=cmd_type,json=cmdType,proto3" json:"cmd_type,omitempty"`       // 0 = upstream req, 1 = upstream rsp (reply to req), 2 = downstream push, 3 = downstream ack (reply to push).
	Cmd       string `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`                               // Command identifier.
	SeqNo     uint32 `protobuf:"varint,4,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`             // Monotonically increasing per-direction sequence id; upstream does not distinguish req/ack, downstream does not distinguish rsp/push.
	MsgId     string `protobuf:"bytes,5,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`              // Message id used to correlate upstream req/rsp pairs and to uniquely identify each push. UUID-based.
	Module    string `protobuf:"bytes,6,opt,name=module,proto3" json:"module,omitempty"`                         // Module name.
	Status    int32  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`                       // Status code; only meaningful on upstream rsp frames.
}

func (x *Head) Reset() {
	*x = Head{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmeet_wss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Head) ProtoMessage() {}

func (x *Head) ProtoReflect() protoreflect.Message {
	mi := &file_tmeet_wss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Head.ProtoReflect.Descriptor instead.
func (*Head) Descriptor() ([]byte, []int) {
	return file_tmeet_wss_proto_rawDescGZIP(), []int{0}
}

func (x *Head) GetFrameType() uint32 {
	if x != nil {
		return x.FrameType
	}
	return 0
}

func (x *Head) GetCmdType() uint32 {
	if x != nil {
		return x.CmdType
	}
	return 0
}

func (x *Head) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Head) GetSeqNo() uint32 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

func (x *Head) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Head) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Head) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// WebSocket frame body.
type ConnMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *Head  `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // Protobuf-serialised payload bytes.
}

func (x *ConnMsg) Reset() {
	*x = ConnMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmeet_wss_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnMsg) ProtoMessage() {}

func (x *ConnMsg) ProtoReflect() protoreflect.Message {
	mi := &file_tmeet_wss_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnMsg.ProtoReflect.Descriptor instead.
func (*ConnMsg) Descriptor() ([]byte, []int) {
	return file_tmeet_wss_proto_rawDescGZIP(), []int{1}
}

func (x *ConnMsg) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *ConnMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// WebSocket auth bind request.
type AuthBindReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BizId     string `protobuf:"bytes,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`               // Business id; fixed to "web_hook_cli".
	TokenType string `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`   // Fixed to "access-token".
	Token     string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                            // userinfo accessToken.
	OpenId    string `protobuf:"bytes,4,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`            // Open id.
	CliUniqId string `protobuf:"bytes,5,opt,name=cli_uniq_id,json=cliUniqId,proto3" json:"cli_uniq_id,omitempty"` // CLI unique id.
}

func (x *AuthBindReq) Reset() {
	*x = AuthBindReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmeet_wss_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthBindReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindReq) ProtoMessage() {}

func (x *AuthBindReq) ProtoReflect() protoreflect.Message {
	mi := &file_tmeet_wss_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthBindReq.ProtoReflect.Descriptor instead.
func (*AuthBindReq) Descriptor() ([]byte, []int) {
	return file_tmeet_wss_proto_rawDescGZIP(), []int{2}
}

func (x *AuthBindReq) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *AuthBindReq) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *AuthBindReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthBindReq) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *AuthBindReq) GetCliUniqId() string {
	if x != nil {
		return x.CliUniqId
	}
	return ""
}

// WebSocket auth bind response.
type AuthBindRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode   int32  `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`      // 0 = success, non-zero = failure.
	Msg       string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                              // Error message.
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session id.
	ConnectId string `protobuf:"bytes,4,opt,name=connect_id,json=connectId,proto3" json:"connect_id,omitempty"` // Connection id.
}

func (x *AuthBindRsp) Reset() {
	*x = AuthBindRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmeet_wss_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthBindRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindRsp) ProtoMessage() {}

func (x *AuthBindRsp) ProtoReflect() protoreflect.Message {
	mi := &file_tmeet_wss_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthBindRsp.ProtoReflect.Descriptor instead.
func (*AuthBindRsp) Descriptor() ([]byte, []int) {
	return file_tmeet_wss_proto_rawDescGZIP(), []int{3}
}

func (x *AuthBindRsp) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *AuthBindRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AuthBindRsp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthBindRsp) GetConnectId() string {
	if x != nil {
		return x.ConnectId
	}
	return ""
}

// WebSocket auth refresh request.
type AuthRefreshReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BizId     string `protobuf:"bytes,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`               // Business id; fixed to "web_hook_cli".
	TokenType string `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`   // Fixed to "access-token".
	Token     string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                            // userinfo accessToken.
	OpenId    string `protobuf:"bytes,4,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`            // Open id.
	CliUniqId string `protobuf:"bytes,5,opt,name=cli_uniq_id,json=cliUniqId,proto3" json:"cli_uniq_id,omitempty"` // CLI unique id.
}

func (x *AuthRefreshReq) Reset() {
	*x = AuthRefreshReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmeet_wss_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRefreshReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRefreshReq) ProtoMessage() {}

func (x *AuthRefreshReq) ProtoReflect() protoreflect.Message {
	mi := &file_tmeet_wss_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRefreshReq.ProtoReflect.Descriptor instead.
func (*AuthRefreshReq) Descriptor() ([]byte, []int) {
	return file_tmeet_wss_proto_rawDescGZIP(), []int{4}
}

func (x *AuthRefreshReq) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *AuthRefreshReq) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *AuthRefreshReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthRefreshReq) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *AuthRefreshReq) GetCliUniqId() string {
	if x != nil {
		return x.CliUniqId
	}
	return ""
}

// WebSocket auth refresh response.
type AuthRefreshRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode   int32  `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`      // 0 = success, non-zero = failure.
	Msg       string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                              // Error message.
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session id.
	ConnectId string `protobuf:"bytes,4,opt,name=connect_id,json=connectId,proto3" json:"connect_id,omitempty"` // Connection id.
}

func (x *AuthRefreshRsp) Reset() {
	*x = AuthRefreshRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmeet_wss_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRefreshRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRefreshRsp) ProtoMessage() {}

func (x *AuthRefreshRsp) ProtoReflect() protoreflect.Message {
	mi := &file_tmeet_wss_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRefreshRsp.ProtoReflect.Descriptor instead.
func (*AuthRefreshRsp) Descriptor() ([]byte, []int) {
	return file_tmeet_wss_proto_rawDescGZIP(), []int{5}
}

func (x *AuthRefreshRsp) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *AuthRefreshRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AuthRefreshRsp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthRefreshRsp) GetConnectId() string {
	if x != nil {
		return x.ConnectId
	}
	return ""
}

// WebSocket event subscribe request.
type SubscribeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventList   []string `protobuf:"bytes,1,rep,name=event_list,json=eventList,proto3" json:"event_list,omitempty"`         // List of event keys to subscribe to.
	AgentOpenId string   `protobuf:"bytes,2,opt,name=agent_open_id,json=agentOpenId,proto3" json:"agent_open_id,omitempty"` // Agent (子账号) open_id this subscribe is on behalf of; empty for master-only / unrestricted subscriptions.
}

func (x *SubscribeReq) Reset() {
	*x = SubscribeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmeet_wss_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeReq) ProtoMessage() {}

func (x *SubscribeReq) ProtoReflect() protoreflect.Message {
	mi := &file_tmeet_wss_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeReq.ProtoReflect.Descriptor instead.
func (*SubscribeReq) Descriptor() ([]byte, []int) {
	return file_tmeet_wss_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeReq) GetEventList() []string {
	if x != nil {
		return x.EventList
	}
	return nil
}

func (x *SubscribeReq) GetAgentOpenId() string {
	if x != nil {
		return x.AgentOpenId
	}
	return ""
}

// WebSocket event subscribe response.
type SubscribeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0 = success, non-zero = failure.
	Msg  string             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // Error message.
	Data *SubscribeRsp_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`  // Response payload.
}

func (x *SubscribeRsp) Reset() {
	*x = SubscribeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmeet_wss_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRsp) ProtoMessage() {}

func (x *SubscribeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_tmeet_wss_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRsp.ProtoReflect.Descriptor instead.
func (*SubscribeRsp) Descriptor() ([]byte, []int) {
	return file_tmeet_wss_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeRsp) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SubscribeRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SubscribeRsp) GetData() *SubscribeRsp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// WebSocket heart rsp.
type HeartRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeartInterval int32 `protobuf:"varint,1,opt,name=heart_interval,json=heartInterval,proto3" json:"heart_interval,omitempty"` // Heart interval in seconds.
}

func (x *HeartRsp) Reset() {
	*x = HeartRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmeet_wss_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartRsp) ProtoMessage() {}

func (x *HeartRsp) ProtoReflect() protoreflect.Message {
	mi := &file_tmeet_wss_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartRsp.ProtoReflect.Descriptor instead.
func (*HeartRsp) Descriptor() ([]byte, []int) {
	return file_tmeet_wss_proto_rawDescGZIP(), []int{8}
}

func (x *HeartRsp) GetHeartInterval() int32 {
	if x != nil {
		return x.HeartInterval
	}
	return 0
}

type SubscribeRsp_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasSubEventList []string `protobuf:"bytes,1,rep,name=has_sub_event_list,json=hasSubEventList,proto3" json:"has_sub_event_list,omitempty"` // List of event keys currently subscribed.
}

func (x *SubscribeRsp_Data) Reset() {
	*x = SubscribeRsp_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmeet_wss_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRsp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRsp_Data) ProtoMessage() {}

func (x *SubscribeRsp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_tmeet_wss_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRsp_Data.ProtoReflect.Descriptor instead.
func (*SubscribeRsp_Data) Descriptor() ([]byte, []int) {
	return file_tmeet_wss_proto_rawDescGZIP(), []int{7, 0}
}

func (x *SubscribeRsp_Data) GetHasSubEventList() []string {
	if x != nil {
		return x.HasSubEventList
	}
	return nil
}

var File_tmeet_wss_proto protoreflect.FileDescriptor

var file_tmeet_wss_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x6d, 0x65, 0x65, 0x74, 0x5f, 0x77, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x77, 0x73, 0x73, 0x70, 0x62, 0x22, 0xb0, 0x01, 0x0a, 0x04, 0x48, 0x65, 0x61,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x63, 0x6d, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x63, 0x6d, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x6d, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x73, 0x65, 0x71, 0x5f, 0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73,
	0x65, 0x71, 0x4e, 0x6f, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3e, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x1f, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x77, 0x73, 0x73, 0x70, 0x62, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x92, 0x01, 0x0a, 0x0b,
	0x41, 0x75, 0x74, 0x68, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x62,
	0x69, 0x7a, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x69, 0x7a,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x5f, 0x75, 0x6e, 0x69, 0x71, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x55, 0x6e, 0x69, 0x71, 0x49, 0x64,
	0x22, 0x78, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x73, 0x70, 0x12,
	0x19, 0x0a, 0x08, 0x72, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22, 0x95, 0x01, 0x0a, 0x0e, 0x41,
	0x75, 0x74, 0x68, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a,
	0x06, 0x62, 0x69, 0x7a, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62,
	0x69, 0x7a, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x65,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x5f, 0x75, 0x6e, 0x69, 0x71, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x55, 0x6e, 0x69, 0x71,
	0x49, 0x64, 0x22, 0x7b, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x52, 0x73, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22,
	0x51, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22,
	0x0a, 0x0d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x6e,
	0x49, 0x64, 0x22, 0x97, 0x01, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x77, 0x73, 0x73, 0x70, 0x62, 0x2e,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x73, 0x70, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x33, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x2b, 0x0a, 0x12, 0x68, 0x61, 0x73, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x68, 0x61, 0x73,
	0x53, 0x75, 0x62, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x08,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x0e, 0x68, 0x65, 0x61, 0x72,
	0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x68, 0x65, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x42,
	0x2b, 0x5a, 0x29, 0x74, 0x6d, 0x65, 0x65, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x77, 0x73, 0x73, 0x70, 0x62, 0x3b, 0x77, 0x73, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tmeet_wss_proto_rawDescOnce sync.Once
	file_tmeet_wss_proto_rawDescData = file_tmeet_wss_proto_rawDesc
)

func file_tmeet_wss_proto_rawDescGZIP() []byte {
	file_tmeet_wss_proto_rawDescOnce.Do(func() {
		file_tmeet_wss_proto_rawDescData = protoimpl.X.CompressGZIP(file_tmeet_wss_proto_rawDescData)
	})
	return file_tmeet_wss_proto_rawDescData
}

var file_tmeet_wss_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tmeet_wss_proto_goTypes = []any{
	(*Head)(nil),              // 0: wsspb.Head
	(*ConnMsg)(nil),           // 1: wsspb.ConnMsg
	(*AuthBindReq)(nil),       // 2: wsspb.AuthBindReq
	(*AuthBindRsp)(nil),       // 3: wsspb.AuthBindRsp
	(*AuthRefreshReq)(nil),    // 4: wsspb.AuthRefreshReq
	(*AuthRefreshRsp)(nil),    // 5: wsspb.AuthRefreshRsp
	(*SubscribeReq)(nil),      // 6: wsspb.SubscribeReq
	(*SubscribeRsp)(nil),      // 7: wsspb.SubscribeRsp
	(*HeartRsp)(nil),          // 8: wsspb.HeartRsp
	(*SubscribeRsp_Data)(nil), // 9: wsspb.SubscribeRsp.Data
}
var file_tmeet_wss_proto_depIdxs = []int32{
	0, // 0: wsspb.ConnMsg.head:type_name -> wsspb.Head
	9, // 1: wsspb.SubscribeRsp.data:type_name -> wsspb.SubscribeRsp.Data
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tmeet_wss_proto_init() }
func file_tmeet_wss_proto_init() {
	if File_tmeet_wss_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tmeet_wss_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Head); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmeet_wss_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ConnMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmeet_wss_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AuthBindReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmeet_wss_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AuthBindRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmeet_wss_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AuthRefreshReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmeet_wss_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AuthRefreshRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmeet_wss_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmeet_wss_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmeet_wss_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*HeartRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmeet_wss_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeRsp_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tmeet_wss_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tmeet_wss_proto_goTypes,
		DependencyIndexes: file_tmeet_wss_proto_depIdxs,
		MessageInfos:      file_tmeet_wss_proto_msgTypes,
	}.Build()
	File_tmeet_wss_proto = out.File
	file_tmeet_wss_proto_rawDesc = nil
	file_tmeet_wss_proto_goTypes = nil
	file_tmeet_wss_proto_depIdxs = nil
}
